 K-Nearest Neighbours ( KNN )
 1. Supervised Learning Model
 2. Used for both classification and Regression
 3. Can be used for non linear models
 4. new data point : new centre : se k neighbours count krega, majority class category will be assigned to the new datapoint

 k should be odd. This is all knn classifier


 **knn regressor ⁉**

 k nearest datapoints ki values ka average will be value of the new unknown datapoint

In [ ]:
# Advantages of knn

1. works well with smaller datasets with less number of features
2. easy to implement for multi-class classification problems
3. Different distance criteria can be used eg: Euclidian distance, Manhattan Distance

In [1]:
# Disadvantages of knn

1. Chosing optimum k value
2. Less efficient with high dimensional data
3. Does not perfom well on imbalanced datasets
4. Sensitive to outliers

1. Euclidian Distance  

sqrt((x2-x1)^2 + (y2-y1)^2) : shortest distance between A and B

2. Manhattan Distance

d= | x2-x1 | + |y2-y1 |


Manhattan distance is preferred over Euclidian distance when there is **high dimensionality** in data. as it can deal with complex directions, that eucledian one cannot do.




# Calculating Euclidean and Manhattan distances in python

In [2]:
p2 = (2,2)
p1 = (1,1)

In [4]:
import numpy as np
euclidean_dist = np.sqrt((p1[0]-p2[0])**2 + (p1[0]-p2[0])**2)
print(euclidean_dist)
# euclidean_dist b/w points in 2 dimensions

1.4142135623730951


In [6]:
p1 = (1,1,1)
p2 = (2,2,2)

e_d = np.sqrt( (p2[0]-p1[0])**2 + (p2[1]-p1[1])**2 + (p2[2]-p1[2])**2 )
e_d
# euclidean distance b/w points in 3 dimensions

1.7320508075688772

In [15]:
p1 = (1,1,1,1)
p2 = (2,2,2,2)

# implementing eucidean distance using for loop, when we have higher number of dimensions

dist = 0

for i in range(len(p1)):
  dist = dist + (p1[i]-p2[i])**2

euclidean_distance = np.sqrt(dist)
print(euclidean_distance)

# sqrt() function math library se bhi use kr skte hain

2.0


In [10]:
# creating a function for calculating eucledian distance

In [17]:
def get_euclidean_distance(p1,p2):
  dist = 0

  for i in range(len(p1)):
    dist = dist + (p1[i]-p2[i])**2

  euclidean_distance = np.sqrt(dist)
  print(euclidean_distance)

# be careful with indentation

In [18]:
get_euclidean_distance((1,1,1),(2,2,2))

1.7320508075688772


# Manhattan Distance

In [21]:
def get_manhattan_distance(p1,p2):
  dist = 0

  for i in range(len(p1)):
    dist = dist + abs(p1[i]-p2[i])

  print(dist)

# sara code function ki indentation me rhe, be careful

# be careful with indentation

In [20]:
get_manhattan_distance((1,1,1,1),(2,2,2,2))

4


calculating distance between two data points : of heart disease dataset

In [22]:
# distance between two similar data points : target 1 vale

# Important point to notice : each feature will work as x_i . so number of features = number of (x2-x1)**2 or |x2-x1| terms in the euclidean or manhattan distance formula

print(get_euclidean_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(37,1,2,130,250,0,1,187,0,3.5,0,0,2)))
print(get_manhattan_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(37,1,2,130,250,0,1,187,0,3.5,0,0,2)))

50.640300157088326
None
100.2
None


In [24]:
# distance between two dissimilar data points : target 1 and 0 vale

print(get_euclidean_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(67,1,0,160,286,0,0,108,1,1.5,1,3,2)))
print(get_manhattan_distance((63,1,3,145,233,1,0,150,0,2.3,0,0,1),(67,1,0,160,286,0,0,108,1,1.5,1,3,2)))

69.54595602908914
None
124.8
None


In [25]:
## similar type datapoints : both distances low comparatively
## dissimilar type datatypes : both distances high comparatively

In [43]:

# pretty different model : lazzy model : logistic svm etc se totally different
# there is nothing like fit in knn classification. hr bar puri distances calculate hongi and least k distance vale elements will be picked, unke labels ka analysis hoga and final class for test_data(single element) will be predicted

In [60]:
# neeche knn code ko bde patience ke sath padhe, samjh aa jayega. Patience rakhiyega. This code is completely different from the implementations of other ML models
# abhi se yad rkho :  distance_list = [] is list of tuples. Na ki list of 1,2,3 like this. each tuple is like = ( (f1,f2,f3,f4,....,fn,target), d ) where d is distance of test_data to that data_point jiske all features are written in (f1,f2,f2..,fn)
# and Most Important : hm distance ke rup me : test_data ke features f_i ki available datapoint ke respective feature f_i se distance nikalte hain(for all features), ye koi physical distance nhi hoti hai.
# aur ek bat, X_TRAIN input me bhi features and labels dono de dena hai, features ka use upar ke 3 functions me hoga( jo len -1 lagakar manage ho jayega) nad label column ka use 4th function me hoga( jo -1 indexing ke dvara use me liya jayega)
import numpy as np
import statistics

class KNN_Classifier():

  # Initiating the parameters
  def __init__(self, distance_metric):
    self.distance_metric = distance_metric



  # Getting the distance metric
  # get_distance_metric just gives the distance between two points : available options are : euclidean and manhattan only : [ remember here x_i's are all the features. This distance is mutidimensional and this this not the actual physical distance, but distane between points having each coordinate as one feature value]

  def get_distance_metric(self, training_data_point, test_data_point):
    if (self.distance_metric == 'euclidean'):
      dist = 0
      # Calculate Euclidean distance between two data points
      for i in range(len(training_data_point) - 1): # -1, since target column ko x_i ke rup me include nhi krna hai, only features has to be dimensions for being included in calulating the distance
        dist = dist + (training_data_point[i] - test_data_point[i])**2
      euclidean_dist = np.sqrt(dist)
      return euclidean_dist
    elif (self.distance_metric == 'manhattan'):
      dist = 0
      # Calculate Manhattan distance between two data points
      for i in range(len(training_data_point) - 1): # again -1, since last column label hai , use include nhi krna as a feture for distance calculation
        dist = dist + abs(training_data_point[i] - test_data_point[i])
      manhattan_dist = dist
      return manhattan_dist



  # Getting the nearest neighbors
  def nearest_neighbors(self, X_train, test_data, k): # remember 'test_data' is single point, not equivalent to y_train. Isi point ko hme classify krna hai.
    distance_list = [] #an array of tuples, whose first element(0th index) is the data point and second element(1st index) is the distance of that training datapoint to the unknown new datapoint(i.e. test_data)

    # Calculate distances from the test_data point to all training data points : test data is only one, jiski jankari hme leni hai ki vo kis class me lie karega.keval usi ek point ki distance all other points se nikalana hai
    for training_data in X_train: # for all elements in x_train ( x_train me sare features hain, with the label, label ka neeche prediction me use hai, distance calculation me -1 lagake unhe exclude kr diya gya hai)
      distance = self.get_distance_metric(training_data, test_data)
      distance_list.append((training_data, distance)) # hr ek point se, us unknown point ki jo distance aayegi, that will be appended in distance_list array in form of tuple.
      # sahi se dekho, distance_list me tuple is appended, not single distance as an element. Keval single distances store krenge to ptha kaise chalega after sorting ki kis datapoint ki distance thi vo.
      # at the end hme vo datapoints hi return krne hain, bad me un deta points ke labels ki analysis hogi, and max number vali category hamare test_data ko assign ho jayegi

    # Sort the distances and select the top k neighbors
    distance_list.sort(key=lambda x: x[1])
    # This line of code sorts the distance_list based on the second element (x[1]) of each element (a tuple) in the list

    # ab in top k distance ke corresponding datapoints ko hi as a output dene ke liye, ek aur array banao and first k tuples ke first element i.e. data_point ko store krke return kr do
    # obviously data_point means all the values of its features
    neighbors_list = [] # that will be list of datapoints = assume it as 2D array, because it is going to be list of 1D arrays => effectively a table bol skte hain
    for j in range(k): # see for loop keval k times hi chalega = k nearest neighbors me padne vale hi datapoints are being stored.
      neighbors_list.append(distance_list[j][0]) # first element of each tuple, i.e. datapoint from the sorted distance_list array is now being stored in neighbour_list array
    return neighbors_list # so finally k nearest neighbours ke sbhi datapoints are returned



  # Predict the class of the new data point
  def predict(self, X_train, test_data, k):
    neighbors = self.nearest_neighbors(X_train, test_data, k) # neighbors array will get to store the k nearest datapoints of the new(test_data) datapoint

    # Create an empty list to store the labels of these k points
    label = []

    for data in neighbors:
      # Append the last element (class label) of each neighbor to the label list : assuming ki datapoint ka last column hi labels/target ko store krta hai
      label.append(data[-1]) # -1 => negative indexing = last column # here we are using the labels, only one place pr. for all rows in neighbours 2D array, store their last elements in the label array

    # Find the most common class label among the neighbors
    predicted_class = statistics.mode(label)

    return predicted_class




1. distance_list.sort(key=lambda x: x[1]):

 This line of code sorts the distance_list based on the second element (x[1]) of each element (a tuple) in the list. In this context, distance_list contains tuples where the first element of each tuple is a training data point, and the second element is the corresponding distance from the test data point. Sorting by x[1] means that the list will be sorted based on the distances.

2. distance_list[j][0]: After sorting distance_list, this code retrieves the training data point from the j-th element of the sorted list. The [j] index selects the j-th element of the list, and the [0] index within that element retrieves the first element of the tuple, which is the training data point. This code is used to extract the k nearest neighbors from the sorted list.

so remember distance_list is an array of tuples, whose first element(0th index) is the data point and second element(1st index) is the distance of that training datapoint to the unknown new datapoint(i.e. test_data)

# ML project using our knn classifier to predict the class of new data point(infact new dat point dena = uske sare features roper order me dena)

In [44]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [45]:
diabetes_dataset = pd.read_csv('/content/diabetes.csv')

In [46]:
diabetes_dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [47]:
diabetes_dataset.shape

(768, 9)

In [48]:
X = diabetes_dataset.drop(columns = 'Outcome', axis = 1)
Y = diabetes_dataset['Outcome']
# separation of features and target is important for train test ssplit function

In [49]:
# converting the data to numpy array

In [50]:
# converting the data to numpy array
X = X.to_numpy()
Y = Y.to_numpy()

In [51]:
print(X)
print(Y)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]
[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0
 1 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0
 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1
 1 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0
 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1
 0 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 1 1 1 0 0
 1 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 0

In [52]:
# train test split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [53]:
print(X.shape, X_train.shape, X_test.shape)

(768, 8) (614, 8) (154, 8)


In [54]:
print(X_train) # clearly 2D array, without target

[[0.00e+00 1.19e+02 0.00e+00 ... 3.24e+01 1.41e-01 2.40e+01]
 [6.00e+00 1.05e+02 7.00e+01 ... 3.08e+01 1.22e-01 3.70e+01]
 [1.00e+00 1.89e+02 6.00e+01 ... 3.01e+01 3.98e-01 5.90e+01]
 ...
 [1.10e+01 8.50e+01 7.40e+01 ... 3.01e+01 3.00e-01 3.50e+01]
 [4.00e+00 1.12e+02 7.80e+01 ... 3.94e+01 2.36e-01 3.80e+01]
 [0.00e+00 8.60e+01 6.80e+01 ... 3.58e+01 2.38e-01 2.50e+01]]


In [55]:
X_train = np.insert(X_train, 8, Y_train, axis=1) # target ko bhi training data me dala ja rha , knn me ye kya ho rha, 9th column pr target ghusa rhe

In [56]:
print(X_train)

[[0.00e+00 1.19e+02 0.00e+00 ... 1.41e-01 2.40e+01 1.00e+00]
 [6.00e+00 1.05e+02 7.00e+01 ... 1.22e-01 3.70e+01 0.00e+00]
 [1.00e+00 1.89e+02 6.00e+01 ... 3.98e-01 5.90e+01 1.00e+00]
 ...
 [1.10e+01 8.50e+01 7.40e+01 ... 3.00e-01 3.50e+01 0.00e+00]
 [4.00e+00 1.12e+02 7.80e+01 ... 2.36e-01 3.80e+01 0.00e+00]
 [0.00e+00 8.60e+01 6.80e+01 ... 2.38e-01 2.50e+01 0.00e+00]]


In [57]:
X_train.shape

(614, 9)

In [58]:
print(X_train[:,8]) # index 8 ka column is being printed, that is labels

[1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.
 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1.
 0. 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1.
 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.
 0. 1. 1. 0. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 0.
 0. 0. 0. 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.
 0. 1. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 0. 1. 0. 0.
 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0.

X_train --> training data with features and target

X_test  --> test data without target, should be a single point, 1 at a time is processed by knn

Model Training : KNN Classifier

In [74]:
classifier = KNN_Classifier(distance_metric='manhattan') # manhattan gives better prediction than euclidean

NOTE: The KNN CLassifier can predict the label for only one data point at a time

In [62]:
prediction = classifier.predict(X_train, X_test[2], k=5) # 2nd datapoint ke liye prediction kiya ja rha hai

In [63]:
print(X_test[2]) # 2nd datapoint with all its features. (no target/label)

[  5.    147.     78.      0.      0.     33.7     0.218  65.   ]


In [64]:
print(Y_test[2])

0


In [65]:
print(prediction)

0.0


In [66]:
X_test.shape

(154, 8)

In [67]:
X_test_size = X_test.shape[0]
print(X_test_size)

154


In [75]:
y_pred = []

for i in range(X_test_size): # for loop chalake , individually prediction ho rha hai, each test data ka and unke outputs ko y_pred array me store kiya ja rha hai
  prediction = classifier.predict(X_train, X_test[i], k=10) # lets take k = 10, as 10 fold cross validation are preferred. But cross validation ka knn se koi mtlab nhi hai fir bhi 10 le lete hain
  y_pred.append(prediction)

In [76]:
print(y_pred)

[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0]


In [77]:
y_true = Y_test

Model Evaluation

In [78]:
accuracy = accuracy_score(y_true, y_pred)

In [79]:
print(accuracy*100)  # accuracy score in %

72.07792207792207


In [80]:
# 78 % accurate model(k=5 pr)

In [ ]:
# 72 % accuracy at k = 10, accuracy ghat gyi