In [1]:
2+2

4

In [2]:
import torch

In [3]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.1
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.13.1
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
b

TENSORS

* A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

* Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

* default data type of float32.( numpy array ka default dtype float 64 hota hai)

* More suitable for deep learning than a numpy array.

* tensor = General form of vector/array. 0D TENSOR is scaler, 1D tensor = vector, 2D tensor = GRID/MATRIX, etc.

In [5]:
import torch
import numpy as np

**LISTS**

In [6]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [7]:
my_list2=[[1,2,3,4],[5,6,7],[8,9],[10]]

In [8]:
my_list2

[[1, 2, 3, 4], [5, 6, 7], [8, 9], [10]]

**NUMPY ARRAY**

In [10]:
np1 = np.random.rand(3,4) # float64 me numpy array

In [11]:
np1

array([[0.5088241 , 0.64173471, 0.34996946, 0.00728599],
       [0.37980346, 0.04691452, 0.99375381, 0.98911648],
       [0.96878797, 0.60366704, 0.89023951, 0.80198787]])

In [12]:
np1.dtype

dtype('float64')

powerfullness : list < numpy array < tensor

In [24]:
np2 = np.random.randint(0,20,size=(3,4))
np2

array([[ 0,  3, 13,  9],
       [ 2,  0,  3,  2],
       [ 1,  6, 17,  9]])

In [26]:
np2.shape

(3, 4)

In [27]:
np2.dtype

dtype('int64')

**TENSORS**

In [14]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.2611,  0.1918, -0.4570, -0.1339],
        [-1.3067,  1.0013,  0.1007, -0.9323],
        [ 1.1846, -0.3370, -0.9737,  0.3199]])

In [15]:
tensor_1d = torch.randn(1,4)

In [16]:
tensor_1d

tensor([[ 0.2014,  0.3300,  0.4137, -0.1851]])

In [17]:
tensor_1d.shape

torch.Size([1, 4])

In [18]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
print(tensor_3d.shape)

torch.Size([2, 3, 4])


In [23]:
tensor_3d.dtype  # ye float 32 hai

torch.float32

In [21]:
## Creating a tonsor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5088, 0.6417, 0.3500, 0.0073],
        [0.3798, 0.0469, 0.9938, 0.9891],
        [0.9688, 0.6037, 0.8902, 0.8020]], dtype=torch.float64)

In [22]:
my_tensor.dtype # numpy array se tensor banane pr dtype float 32 nhi, 64 hota hai, as dtype of numpy array is float

torch.float64

In [28]:
# let's create tensor of integer numpy
myy_tensor = torch.tensor(np2)
myy_tensor

tensor([[ 0,  3, 13,  9],
        [ 2,  0,  3,  2],
        [ 1,  6, 17,  9]])

In [29]:
myy_tensor.dtype  # so now it is integer tensor, So jaisa dtype numpy array ka hoga , same vahi tensor ka bhi ho jayega

torch.int64

**Tensor Operations in DEEP Learning**

In [30]:
import torch

In [31]:
my_torch = torch.arange(10) # similar to numpy, 10 excluded

In [32]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
my_torch.shape

torch.Size([10])

In [34]:
my_torch.dtype

torch.int64

In [35]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [39]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
my_torch2 = my_torch2.reshape(2,-1) # -1 = jb pta na ho ki 2*x = total number of elements, me x kya hai, nhi ptha
my_torch2 # -1 likhne se number of columns apne aap define ho jayenge, if krne layak honge to, x*y = total number of elements hone pr, othrwise error

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [42]:
# incompetible size error demonstration
my_torchh = torch.arange(10)
my_torchh

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
my_torchh = my_torchh.reshape(2,6) # total 12 elements required, available 10 only
my_torchh

RuntimeError: ignored

In [44]:
myy_torchh = np.arange(15)
myy_torchh

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [45]:
myy_torchh = myy_torchh.reshape(2,-1)
myy_torchh

ValueError: ignored

In [48]:
myy_torchh = myy_torchh.reshape(3,-1)
myy_torchh

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
torch_1 = torch.arange(10)

In [50]:
torch_1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
torch_2 = torch_1.reshape(-1,5) # this time, first coordinate -1 = number of rows automatic determine krega
torch_2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

**VIEW COMMAND**

VIEW and RESHAPE are quite similar.

In [52]:
 torch_2 = torch.arange(10)
 torch_2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
torch_3 = torch_2.view(2,5)
torch_3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

DIFFERENCE BETWEEN VIEW AND RESHAPE

In [59]:
import torch

# Original tensor
original_tensor = torch.arange(1, 7)
print("original tensor:" ,original_tensor)

# Using view
viewed_tensor = original_tensor.view(2, 3)
print("viewed_tensor",viewed_tensor)

# Using reshape
reshaped_tensor = original_tensor.reshape(2, 3)
print("reshaped_tensor",reshaped_tensor)



original tensor: tensor([1, 2, 3, 4, 5, 6])
viewed_tensor tensor([[1, 2, 3],
        [4, 5, 6]])
reshaped_tensor tensor([[1, 2, 3],
        [4, 5, 6]])


In [60]:
# modifi the reshapes tensor and look at the original tensor
reshaped_tensor[0,0] = 44

print("After modifying the reshaped_tensor, reshaped_tensor is", reshaped_tensor)
print("After modifying the reshaped tensor, viewed_tensor is", viewed_tensor)
print("After mofyfing the reshaped_tensor, original_tensor is", original_tensor)

# so reshaped ko change krne pr viewed, original, sare tensors change ho gye, it's kind of reshape me original address pass ho jata hai, So all changed ho gye

After modifying the reshaped_tensor, reshaped_tensor is tensor([[44,  2,  3],
        [ 4,  5,  6]])
After modifying the reshaped tensor, viewed_tensor is tensor([[44,  2,  3],
        [ 4,  5,  6]])
After mofyfing the reshaped_tensor, original_tensor is tensor([44,  2,  3,  4,  5,  6])


In [62]:
# Modify the viewed tensor
viewed_tensor[0, 0] = 55

print("Original Tensor:", original_tensor)
print("Viewed Tensor:", viewed_tensor)
print("Reshaped Tensor:", reshaped_tensor)

# View me bhi chage krnee se, original, reshaped and viewed teeno tensors changed ho gye.So dono(view, reshape) direct address store kr rhe hain c++ ke pointer ki tarah. Koi copy nhi bana rha

Original Tensor: tensor([55,  2,  3,  4,  5,  6])
Viewed Tensor: tensor([[55,  2,  3],
        [ 4,  5,  6]])
Reshaped Tensor: tensor([[55,  2,  3],
        [ 4,  5,  6]])


Your observation is indeed correct. I appreciate your detailed experiment, and it helps to clarify the behavior of `view` and `reshape` in PyTorch.

In recent versions of PyTorch (1.7.0 and later), the `reshape` function is made to behave similarly to `view` in terms of memory sharing. This is different from earlier versions where `reshape` would generally create a contiguous copy of the tensor.

In both your cases (modifying the reshaped tensor and modifying the viewed tensor), changes are reflected in the original tensor, and this is because both `view` and `reshape` are providing views into the original data rather than creating new copies.

It's important to note that while `view` and `reshape` may behave similarly in many cases, there can be subtle differences in their behavior, especially when dealing with non-contiguous tensors. However, in your example, the tensors are contiguous, and modifications to one affect the others because they share the same memory. Thank you for providing a hands-on example that demonstrates this behavior.

**Contiguous vs Non-contiguous tensors**

In the context of tensors, "contiguous" refers to the arrangement of elements in memory. A contiguous tensor is one where the elements are stored in a single, contiguous block of memory. This means that the elements are laid out next to each other in a sequential manner. Contiguous tensors are typically more memory-efficient and allow for faster access to elements.

On the other hand, a non-contiguous tensor is one where the elements are not stored in a single, contiguous block of memory. Instead, there may be gaps or strides between the elements, making the layout more complex. Non-contiguous tensors can arise in various situations, such as when performing certain operations or slicing on a tensor.

Here's a brief explanation of contiguous and non-contiguous tensors with a simple example:

1. **Contiguous Tensor:**
   ```python
   import torch

   # Creating a contiguous tensor
   cont_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
   ```

   In this case, the tensor is contiguous because the elements are stored in a single block of memory.

2. **Non-Contiguous Tensor:**
   ```python
   import torch

   # Creating a non-contiguous tensor using slicing
   cont_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
   non_cont_tensor = cont_tensor[:, 1:]
   ```

   In this case, the `non_cont_tensor` is not contiguous because it is a result of a slicing operation.

When working with operations that require contiguous memory, such as some PyTorch functions or certain hardware optimizations, it's important to be aware of the contiguity of your tensors. In many cases, you can use the `contiguous` method to ensure that a tensor is contiguous.

```python
non_cont_tensor = non_cont_tensor.contiguous()
```

This method creates a contiguous copy of the tensor, resolving any issues related to non-contiguity. However, keep in mind that creating a contiguous copy might involve copying the data, so it's best to avoid unnecessary use of `contiguous` if performance is a concern.




In [63]:
# with reshape and view, they will update in both the directions
torch5=torch.arange(10)
torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
torch6 = torch5.reshape(2,5)
torch7 = torch5.reshape(2,5)
print(torch6,torch7)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]) tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [68]:
torch5[0] = 88
print(torch5)
print(torch6)
print(torch7)

tensor([88,  1,  2,  3,  4,  5,  6,  7,  8,  9])
tensor([[88,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])
tensor([[88,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])


So original me change krne se sbme change ho gya , in the same way,

**kisi bhi ek : original or view or reshape me change krne pr sbme change ho jata hai**

SLICES

In [69]:
torch1 = torch.arange(10)
torch1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
torch1[7] # Grab a specific item by index

tensor(7)

In [71]:
#Grab Slice
torch2 = torch1.reshape(5,2)

In [72]:
torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [73]:
# grabbing the 2nd column : 1st index ka column
torch2[:,1] # in a row/list

tensor([1, 3, 5, 7, 9])

In [74]:
# return a column
torch2[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [75]:
torch3 = torch2[:,1:]

In [76]:
torch3

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [77]:
torch3.shape

torch.Size([5, 1])

5, 1D arrays of shape 1 = A 2D ARRAY/MATRIX OF JUST ONE COLUMN

**BASIC SLICING OPERATIONS IN TENSOR**

Certainly! Tensor slicing operations in PyTorch allow you to extract specific portions of a tensor. Slicing is a powerful and flexible way to work with subsets of data. Here are some basics of tensor slicing:

### Basic Slicing:

You can use the colon `:` operator to perform basic slicing. The syntax is similar to slicing in Python lists.

```python
import torch

# Create a tensor
tensor_data = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice rows and columns
slice1 = tensor_data[1, :]  # Second row
slice2 = tensor_data[:, 1]  # Second column
slice3 = tensor_data[0:2, 1:3]  # Rows 0 to 1, columns 1 to 2

print("Slice 1:", slice1)
print("Slice 2:", slice2)
print("Slice 3:", slice3)
```

### Advanced Indexing:

You can use advanced indexing to select specific elements based on a condition or a list of indices.

```python
# Advanced indexing
mask = tensor_data > 5
advanced_slice = tensor_data[mask]

print("Advanced Slice:", advanced_slice)
```

### Using `slice`:

You can use the `slice` function to create more complex slices.

```python
# Using slice function
rows = slice(0, 2)  # Equivalent to 0:2
columns = slice(1, 3)  # Equivalent to 1:3
slice4 = tensor_data[rows, columns]

print("Slice 4:", slice4)
```

### Modifying Slices:

You can modify slices directly, and the changes will reflect in the original tensor.

```python
# Modifying slices
tensor_data[1, :] = torch.tensor([10, 11, 12])  # Modify the second row
tensor_data[:, 2] = 0  # Set the third column to zeros

print("Modified Tensor:", tensor_data)
```

These are just some basics of tensor slicing in PyTorch. Slicing is a flexible and powerful tool, and you can combine these operations to extract the exact portions of the data you need. Keep in mind that PyTorch tensor slicing is similar to NumPy slicing and follows similar principles.

In [78]:
import torch

# Create a tensor
tensor_data = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice rows and columns
slice1 = tensor_data[1, :]  # Second(i=1) row , will be returned as 1D tensor
slice2 = tensor_data[:, 1]  # Second(i=1) column will be returned as 1D Tensor
slice3 = tensor_data[0:2, 1:3]  # Rows 0 to 1, columns 1 to 2 , will be returned as 2D tensor as it is

print("Slice 1:", slice1)
print("Slice 2:", slice2)
print("Slice 3:", slice3)

Slice 1: tensor([4, 5, 6])
Slice 2: tensor([2, 5, 8])
Slice 3: tensor([[2, 3],
        [5, 6]])


In [81]:
print(slice1.dtype)
print(slice1.shape)

torch.int64
torch.Size([3])


In [82]:
# Advanced indexing
mask = tensor_data > 5
advanced_slice = tensor_data[mask]

print("Advanced Slice:", advanced_slice) # will be returned in 1D tensor all the elements of tensor which are greater than 5

Advanced Slice: tensor([6, 7, 8, 9])


In [87]:
# Using slice function
rows = slice(0, 2)  # Equivalent to 0:2
columns = slice(1, 3)  # Equivalent to 1:3

slice4 = tensor_data[rows, columns]

print(tensor_data)
print(rows)
print(tensor_data[0:2]) # index 0 to 1 ki rows will be grabbed
print(columns)
print(tensor_data[1:3]) # to grab rows from index 1 to 2. Bina ',' ke keval rows grab hongi
print("Slice 4:", slice4)

print(tensor_data[:,1:3]) # all rows, but 1 to 2 index ke coulmns
print(tensor_data[1:3,:]) # same as tensor_data[1:3] , will grab all columns of rows from 1 to 2 , inclusive; Last index removed

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
slice(0, 2, None)
tensor([[1, 2, 3],
        [4, 5, 6]])
slice(1, 3, None)
tensor([[4, 5, 6],
        [7, 8, 9]])
Slice 4: tensor([[2, 3],
        [5, 6]])
tensor([[2, 3],
        [5, 6],
        [8, 9]])
tensor([[4, 5, 6],
        [7, 8, 9]])


So jb kbhi bhi bhulna toh , tensor[1:5 , : ] and tensor[ : , 1:5 ] krke check kr lena original data set pr.

tensor[ : , 1:5] = all full columns from 1 to 4 index

tensor[ 1:5, : ] = all full rows from index 1 to 4. Is case me tensor[1:5] will also do the same.

tensor[ 1:4 , 2:8 ] = 2D dataframe in which rows from index 1 to 3, and columns from index 2 to 7 from the original tensor.

**Basic Maths Operations on tensors**

- Add, Subtract, Multiply, Divide, Remainders, Exponents
- Shorthand and uh, Longhand
- Reassignment

In [88]:
import torch

In [136]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [137]:
# Addition : shorthand
tensor_a + tensor_b # similar to numpy array. Keval list me concatenate hota hai.

tensor([ 6,  8, 10, 12])

In [138]:
# Addition Longhand : similar to numpy.add(np1,np2)
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [139]:

# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [140]:
# Sub Function
print(torch.sub(tensor_b, tensor_a))
print(torch.subtract(tensor_b, tensor_a))

tensor([4, 4, 4, 4])
tensor([4, 4, 4, 4])


In [141]:
# Multiplication : element by element
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [142]:
# Mul longhand  element by element
print(torch.mul(tensor_a, tensor_b))
print(torch.multiply(tensor_a,tensor_b)) # mul is alias of multiply function,  similarly sub

tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])


In [143]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [144]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [145]:
torch.divide(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [146]:
# Remainder : Modulus
tensor_b % tensor_a # gives list of remainders

tensor([0, 0, 1, 0])

In [147]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [148]:
# Exponent / power
tensor_a**tensor_b # a^b : 1^5, 2^6, 3^7, 4^8

tensor([    1,    64,  2187, 65536])

In [149]:
#Longhand remainder
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [150]:
torch.power(tensor_a,tensor_b) # dokha, pow() is valid function, but power() is not a function

AttributeError: ignored

In [151]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [152]:
tensor_a.sub(tensor_b)

tensor([-4, -4, -4, -4])

In [153]:
tensor_a.mul(tensor_b)

tensor([ 5, 12, 21, 32])

In [154]:
tensor_a.div(tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [155]:
tensor_a.remainder(tensor_b)

tensor([1, 2, 3, 4])

In [156]:
tensor_a.pow(tensor_b) # a^b

tensor([    1,    64,  2187, 65536])

In [157]:
# reassignment_

In [158]:
tensor_a

tensor([1, 2, 3, 4])

In [159]:

# tensor_a = tensor_a + tensor_b

# aliter : add_   (add_underscore)

tensor_a.add_(tensor_b) # only torch1.add_(tensor2) chalega , torch.add_(tensor1,tensor2) nhi chalega

tensor([ 6,  8, 10, 12])

In [160]:
tensor_a

tensor([ 6,  8, 10, 12])

In [161]:
tensor_a.sub_(tensor_b)

tensor([1, 2, 3, 4])

In [162]:
tensor_a

tensor([1, 2, 3, 4])

In [163]:
tensor_a.mul_(tensor_b) # = , tensor_a = tensor_a * tensor_b, instant effect

tensor([ 5, 12, 21, 32])

In [164]:
tensor_a

tensor([ 5, 12, 21, 32])

In [165]:
tensor_a.div_(tensor_b)  # won't work for division directly,

RuntimeError: ignored

In [166]:
tensor_a.dtype

torch.int64

In [167]:
tensor_b.dtype

torch.int64

since a me change krna hai and output float hoga, so a ka dtype float kro pahle

In [168]:
tensor_a = tensor_a.float()
tensor_a.div_(tensor_b)

tensor([1., 2., 3., 4.])

In [169]:
# or dono ko float kr lo, but no need since a me change hona hai, a ka float hona imp hai bs