In [1]:
# numpy = numerical python


In [2]:
import numpy as np

In [3]:
# list vs numpy : time taken
from time import process_time

In [7]:
python_list=[i for i in range(1000000)] # 1 M
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.09869936499999987


In [8]:
np_array=np.array([i for i in range(1000000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0010809200000005958


In [10]:
# kitna time save hua : 0.098/0.001
0.098/0.001 # 98 times, tumhara time save hua. 100 times less time lga numpy array me same operation krne me as list


98.0

In [12]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [14]:
b=np.array([(1,2,3,4),(5,6,7,8)]) # 2D array using tuples / list
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [15]:
c=np.array([[1,2,3,4],[5,6,7,8]],dtype=float)
c

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [16]:
# initial placeholders
x=np.zeros((4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
y=np.ones((4,6))
y

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
z=np.full((5,4),99)
z

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99],
       [99, 99, 99, 99]])

In [20]:
# create an identity matrix : all diagonal 1, other 0 : identity ,atrix are only square matrices
a=np.eye(5)
a


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
# numpy array with random values
b=np.random.random((3,4))
b # all values between 0 and 1 , everytime different

array([[0.82359152, 0.3504192 , 0.68809152, 0.71386757],
       [0.26418895, 0.38197167, 0.83649576, 0.55823461],
       [0.15644042, 0.09679734, 0.912766  , 0.78979122]])

In [24]:
# random array/matrix within a specific range
c=np.random.randint(10,100,(3,5))
print(c)

[[46 65 81 87 23]
 [29 14 31 59 46]
 [18 85 86 45 56]]


In [27]:
# array of evenly spaced values:
d=np.linspace(10,30,10)
print(d) # 10 evely spaced value, 10 and 30 included

[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]


In [28]:
e=np.arange(10,30,10) # integer values, 10-10 ke gap pe, end not included,
e

array([10, 20])

In [30]:
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
print(type(np_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [31]:
c=np.random.randint(10,90,(5,5))

In [32]:
c

array([[27, 86, 22, 12, 48],
       [50, 36, 65, 68, 32],
       [66, 72, 67, 23, 77],
       [71, 37, 52, 17, 83],
       [70, 50, 14, 62, 40]])

# Analysing C numpy array

In [33]:
print(c.ndim)

2


In [34]:
print(c.shape)

(5, 5)


In [35]:
print(c.size)

25


In [36]:
print(c.dtype)

int64


In [39]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2) # another list concatenated of the two lists
# print(list1-list2) error, element wise operations ese 2 lists me nhi kr skte

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [41]:
a=np.random.randint(0,9,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[0 5 0]
 [0 1 5]
 [6 0 1]]
[[15 17 15]
 [15 16 10]
 [13 14 11]]


In [42]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[15 22 15]
 [15 17 15]
 [19 14 12]]
[[-15 -12 -15]
 [-15 -15  -5]
 [ -7 -14 -10]]
[[ 0 85  0]
 [ 0 16 50]
 [78  0 11]]
[[0.         0.29411765 0.        ]
 [0.         0.0625     0.5       ]
 [0.46153846 0.         0.09090909]]


In [45]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 22 15]
 [15 17 15]
 [19 14 12]]
[[-15 -12 -15]
 [-15 -15  -5]
 [ -7 -14 -10]]
[[ 0 85  0]
 [ 0 16 50]
 [78  0 11]]
[[0.         0.29411765 0.        ]
 [0.         0.0625     0.5       ]
 [0.46153846 0.         0.09090909]]


# array manipulation

In [47]:
array=np.random.randint(0,10,(2,3))
print(array)

[[3 7 4]
 [1 2 0]]


In [48]:
print(array.shape)

(2, 3)


In [49]:
transposee=np.transpose(array)
print(transposee)

[[3 1]
 [7 2]
 [4 0]]


In [50]:
print(transposee.shape)

(3, 2)


In [54]:
# reshape : this is not transpose of array. remember it : bs row wise elements ke arrangement ko column wise kr dega
print(array.shape)


(2, 3)


In [52]:
b=array.reshape(3,2)

In [53]:
print(b)
print(b.shape)

[[3 7]
 [4 1]
 [2 0]]
(3, 2)
