In [1]:
import numpy as np


In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,34,45],[20,15,90],[50,64,21]])
print(matrix_2)

[[10 34 45]
 [20 15 90]
 [50 64 21]]


In [5]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [6]:
random_matrices = np.random.rand(3,3) # 3*3 matrix chahiye all random values between 0 to 1
random_matrices

array([[0.23474635, 0.0443468 , 0.54616984],
       [0.57036976, 0.3787059 , 0.88001887],
       [0.99964159, 0.76696963, 0.46839058]])

In [7]:
# random values but all the values with integers
random_integer_matrix = np.random.randint(100,size=(4,5)) # all values < 100
print(random_integer_matrix)

[[ 9 48 57 55 33]
 [ 4 57 65 33 31]
 [91 98 19 68 99]
 [48 91 53 72  3]]


In [8]:
# all values 1 : matrix
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# all values 1 : matrix
matrix_4 = np.ones((8,9),dtype=int)
print(matrix_4)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [10]:
null_matrix=np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# identity matrix
identity_matrix=np.eye(3,3) # np.eye(3) will also work here
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
matrix_5=np.eye(5)
print(matrix_5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
a=np.random.randint(100,size=(4,5))
print(a)

[[25 10 54 62 97]
 [ 9 53 78 43  3]
 [77 83 85 54 71]
 [21 28 76 94 78]]


In [14]:
# transpose of the matrix
transpose_matrix=np.transpose(a)
print(transpose_matrix)

[[25  9 77 21]
 [10 53 83 28]
 [54 78 85 76]
 [62 43 54 94]
 [97  3 71 78]]


In [15]:
matrix_6=np.full((4,5),99)
print(matrix_6)

[[99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]
 [99 99 99 99 99]]


Matrix Operations

In [16]:
import numpy as np

In [17]:
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])

In [18]:
A

array([[2, 3],
       [4, 5]])

In [19]:
print(B)

[[6 7]
 [8 9]]


In [20]:
print(A.shape, B.shape)

(2, 2) (2, 2)


In [21]:
print(A+B)
print(A-B)

[[ 8 10]
 [12 14]]
[[-4 -4]
 [-4 -4]]


In [22]:
# create two matrices with random values
matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(20,size=(3,3))

In [23]:
print(matrix_1, matrix_2)

[[7 4 8]
 [2 7 8]
 [3 4 0]] [[ 3  2  8]
 [15  7 11]
 [ 3  1  0]]


In [24]:
sum = np.add(matrix_1,matrix_2) # alternate of +
print(sum)

[[10  6 16]
 [17 14 19]
 [ 6  5  0]]


In [25]:
print(np.subtract(matrix_1,matrix_2))

[[  4   2   0]
 [-13   0  -3]
 [  0   3   0]]


In [26]:
diff_matrix = matrix_1 - matrix_2
print(diff_matrix)

[[  4   2   0]
 [-13   0  -3]
 [  0   3   0]]


In [27]:
# scaler multiplication
x=5
grid=np.random.randint(5,size=(5,6))
grid

array([[3, 3, 0, 1, 0, 1],
       [0, 3, 4, 3, 1, 0],
       [2, 2, 2, 1, 3, 3],
       [0, 0, 0, 2, 0, 3],
       [3, 3, 1, 3, 2, 2]])

In [28]:
scaler_multiplication = np.multiply(x,grid)
print(scaler_multiplication)

[[15 15  0  5  0  5]
 [ 0 15 20 15  5  0]
 [10 10 10  5 15 15]
 [ 0  0  0 10  0 15]
 [15 15  5 15 10 10]]


Matrix Multiplication

In [29]:
A = np.random.randint(5, size=(3,4))
B = np.random.randint(5, size=(4,2))
# A*B will be of size 3*2

In [30]:
print(A)

[[1 0 2 3]
 [1 2 1 0]
 [4 2 1 0]]


In [31]:
print(B)

[[3 2]
 [0 4]
 [1 2]
 [3 3]]


In [32]:
product = np.dot(A,B) # A*B
print(product)

[[14 15]
 [ 4 12]
 [13 18]]


In [33]:
product.shape

(3, 2)

In [34]:
# m*n and n*p can be multiplies and resultant matrix size = m*p

In [35]:
# number of columns in 1st matrix should be same as the number of rows in second matrix

Another kind of matrix multiplication

In [36]:
# element wise matrix multiplication
# Mathematics me iska koi significance nhi hai
# np.multiply
# similar to addition and subtraction of two matrices
# Both matrices should be of the same size

In [37]:
mat1=np.random.randint(4,size=(4,4))
mat2=np.random.randint(4,size=(4,4))

In [38]:
print(mat1)
print()
print(mat2)

[[3 1 3 1]
 [2 3 1 3]
 [3 1 0 1]
 [1 2 2 1]]

[[1 1 2 3]
 [1 3 2 2]
 [1 1 3 2]
 [2 2 1 3]]


In [39]:
print(np.multiply(mat1,mat2))

[[3 1 6 3]
 [2 9 2 6]
 [3 1 0 2]
 [2 4 2 3]]


In [40]:
print(mat1*mat2)

[[3 1 6 3]
 [2 9 2 6]
 [3 1 0 2]
 [2 4 2 3]]
